name: python compile(Linux&Windows)

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Compile exe
        run: |
          pyinstaller -n copymanga-downloader -F main.py -i icon.ico
      - name : upload exe
        uses: actions/upload-artifact@master
        with:
          name: copymanga-downloader-Linux
          path: dist/copymanga-downloader
  
  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path -path "requirements.txt" -PathType Leaf) {
            pip install -r requirements.txt
          }
      - name: Compile exe
        run: |
          pyinstaller -n copymanga-downloader -F main.py -i icon.ico
      - name : upload exe
        uses: actions/upload-artifact@master
        with:
          name: copymanga-downloader-windows
          path: dist/copymanga-downloader.exe
          
  macos-build:
    runs-on: macos-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v2.4.2
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          pip3 install pyinstaller
          pip3 install -r requirements.txt
          
      - name: Compile
        run: |
          pyinstaller -F main.py
          pyinstaller main.spec
          
      - name : upload artifact
        uses: actions/upload-artifact@master
        with:
          name: macos-latest
          path: dist/

