name: Linux&Windows build

on:
  release:
    types:
      - released
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.json'
      - '*.txt'
      - '.github/workflows/*.yaml'
      - 'setup.py'
      - 'pyproject.toml'
  workflow_dispatch:
jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Compile bin
        run: |
          pyinstaller -n Linux-copymanga-downloader -F main.py -i icon.ico --onefile
      - name: upload bin
        uses: actions/upload-artifact@master
        with:
          name: copymanga-downloader-Linux
          path: dist/
                
      - name: Prepare GH Release Assets
        if: github.event_name == 'release'
        run: |-
          for file in ./dist/*; do
            md5sum ${file#./} >> ${file%.*}.md5
            sha256sum ${file#./} >> ${file%.*}.sha256
          done
          ls -l

      - name: Upload GH Release Assets
        if: github.event_name == 'release'
        uses: shogo82148/actions-upload-release-asset@8f6863c6c894ba46f9e676ef5cccec4752723c1e # v1.9.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/*

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path -path "requirements.txt" -PathType Leaf) {
            pip install -r requirements.txt
          }
      - name: Compile exe
        run: |
          pyinstaller -n Windows-copymanga-downloader -F main.py -i icon.ico --onefile
      - name: upload exe
        uses: actions/upload-artifact@master
        with:
          name: copymanga-downloader-windows
          path: dist/Windows-copymanga-downloader.exe

      - name: Upload GH Release Assets
        if: github.event_name == 'release'
        uses: shogo82148/actions-upload-release-asset@8f6863c6c894ba46f9e676ef5cccec4752723c1e # v1.9.2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/*
