name: Linux&Windows build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - '*.json'
      - '*.txt'
      - '*.yml'
      - '*.yaml'
      - 'setup.py'
      - 'pyproject.toml'
  workflow_dispatch:
jobs:
  linux-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Compile bin
        run: |
          pyinstaller -n Linux-copymanga-downloader -F main.py -i icon.ico --onefile
      - name: upload bin
        uses: actions/upload-artifact@master
        with:
          name: copymanga-downloader-Linux
          path: dist/

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path -path "requirements.txt" -PathType Leaf) {
            pip install -r requirements.txt
          }
      - name: Compile exe
        run: |
          pyinstaller -n Windows-copymanga-downloader -F main.py -i icon.ico --onefile
      - name: upload exe
        uses: actions/upload-artifact@master
        with:
          name: copymanga-downloader-windows
          path: dist/Windows-copymanga-downloader.exe
